### ISSUE TITLE
Can't call function in struct field initializer

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/jakt#1429]
This program does not compile:

```jakt
fn foo() -> i32 {
    return 1
}

struct S {
    f: i32 = foo()
}

fn main() throws {
    let s = S()
}
```

Error:
```
───┬─ tsm.jakt:6:14
 5 │ struct S { 
 6 │     f: i32 = foo() 
   │              ──┬  
   │                ╰─ Call to unknown function: ‘foo’
 7 │ } 
───┴─
```

**Comment by cybergsus** [comment]
I've looked into this. The bug occurs because `typecheck_struct_constructor` (which is run from  `typecheck_namespace_constructors`) tries to create the constructor with the default argument, typechecking it, when `typecheck_function_predecl` passes haven't run yet:
https://github.com/SerenityOS/jakt/blob/2fc0c044de9743a0fbf64cfab2be0b6aed53858c/selfhost/typechecker.jakt#L822-L833

https://github.com/SerenityOS/jakt/blob/2fc0c044de9743a0fbf64cfab2be0b6aed53858c/selfhost/typechecker.jakt#L2651-L2656

The issue is: there's a dependency loop between these two. If I move the`typecheck_namespace_constructor` call a little bit further, a ton of tests (~600) fall apart. I've tried these two methods:
- trying to just use the existing `typecheck_struct_fields` pass, but that started causing issues with the constructor parameters not being defaulted properly: The call to `S()` complained about number of arguments, which suggests that it couldn't get a proper default argument type out of the default value.
- Having a `typecheck_namespace_constructors_predecl` pass that does the same thing as its non-`_predecl` counterpart, except that it just records a `CheckedFunction` with its default parameter values as `Garbage` expressions, to avoid typechecking them until a further pass. This made the call to `S()` result in a "could not find a function with this signature" error, even though the default value "was there". I've thought of adding a type id to `Garbage` so `CheckedExpression::type()` can always spit a `TypeId`, but I had to make it `undefined_type_id` in the rest of the codebase, and I wouldn't still solve the problem.

Any thoughts/help? I'll provide more links if necessary.
