### ISSUE TITLE
No number type inference for negative numbers

### ISSUE THREAD

**Issue by robryanx** [SerenityOS/jakt#1437]
```
fn number_inference() -> i32 {
    return -1
}
```
`Type mismatch: expected ‘i32’, but got ‘i64’`

Would expect this to work as it does for zero or positive numbers and infer i32 type based on the return type.

**Comment by alimpfard** [comment]
That's because `-1` is parsed as `-(1)` (negate op applied to 1), `-` probably doesn't pass the correct type hint :shrug:

**Comment by robryanx** [comment]
Yeah negate doesn't pass any type hint. This used to work and it didn't seem like anything had changed with negate in a long time. So maybe something to do with return, I was going to try it in other cases to see if it infered correctly but didn't get to that.

**Comment by cybergsus** [comment]
The issue is that `infer_signed_int` isn't passed the return type hint, and the data flow is cut here: https://github.com/SerenityOS/jakt/blob/b3cb307777daa24b8b949852310ddd969ed06db5/selfhost/typechecker.jakt#L7645C8-L7646. Passing `type_hint` in both match branches solves the issue, but then the compiler fails to typecheck the `compare` functions because it thinks `u8` can't be converted to `Ordering`, and fails with a bunch of these errors: ```
Error: Type mismatch: expected ‘Ordering’, but got ‘u8’
─────┬─ /home/gsus/jakt/build/include/runtime/jaktlib/prelude/operators.jakt:192:16
 191 │     fn compare(this, anon rhs: T) -> Ordering {
 192 │         return .compare_impl(rhs) as! Ordering
     │                ─────────────────┬
     │                                 ╰─ Type mismatch: expected ‘Ordering’, but got ‘u8’
 193 │     }
─────┴─
Error: Type mismatch: expected ‘Ordering’, but got ‘u8’
```
