### ISSUE TITLE
Cannot use `continue`  inside `match` statement

### ISSUE THREAD

**Issue by lukehoban** [SerenityOS/jakt#402]
Currently, `match` statements compile into automatically-invoked C++ closures.  This means that `continue` statements inside match branches lead to errors  in the C++ code since the `continue` is not inside a loop.

```jakt
function main() {
    let mutable x: Optional<i64> = None
    loop {
        match x {
            None => { 
                x = Some(42)
                continue 
            }
        }
        println("{}", x.value())
        return 1
    }
}

```

Error:
```
/var/folders/yg/4frmdt6j7qj02r6nm7ftdt2w0000gn/T/output155ddf0a-3bee-4fc0-b51c-d6d878e41b92.cpp:18:18: error: 'continue' statement not in loop statement
                 continue;             }
                 ^
```

Current codegen:
```cpp
#include <lib.h>




ErrorOr<int> JaktInternal::main(Array<String>)
{
    using _JaktCurrentFunctionReturnType = ErrorOr<int>;
    {
        Optional<i64> x = JaktInternal::OptionalNone();
        for (;;) {        {
            JAKT_RESOLVE_EXPLICIT_VALUE_OR_RETURN(([&]() -> JaktInternal::ExplicitValueOrReturn<void, _JaktCurrentFunctionReturnType> { 
auto&& __jakt_enum_value = JaktInternal::deref_if_ref_pointer(x);
if (__jakt_enum_value.template has<typename JaktInternal::RemoveRefPtr<Optional<i64>>::None>()) {
auto& __jakt_match_value = __jakt_enum_value.template get<typename JaktInternal::RemoveRefPtr<Optional<i64>>::None>();
             {
                 (x = (static_cast<i64>(42LL)));
                 continue;             }
return JaktInternal::ExplicitValue<void>();
}

return JaktInternal::ExplicitValue<void>();
}()));
            outln(String("{}"),((x).value()));
            return (static_cast<i64>(1LL));
        }
}    }
    return 0;
}
```

**Comment by alimpfard** [comment]
This is a known issue (by me), technically it's not very difficult to implement, but in reality it's a bit of a biggie since `break`/`continue` cannot appear outside loops in C++ _at all_, even in a provably unreachable branch, so `JAKT_RESOLVE_EXPLICIT_VALUE_OR_RETURN` cannot contain them in general.

**Comment by cybergsus** [comment]
I will take this since I have an idea: Change `ExplicitValueOrReturn` to `ExplicitValueOrControlFlow` where `ControlFlow` can be `Return` (with value or void), `Break` or `Continue`

**Comment by maddanio** [comment]
hmm, are you sure you actually want that to work? as it is now match is a statement with a result. doing the continue will only make sense if you dont use the result, otherwise the continue doesnt really seem well defined. i.e. what exactly do you expect to happen here:
`let a = match x { None => continue};`
?

**Comment by maddanio** [comment]
hmm, using cybergsus' idea would work in any case, yes. just feels weird semantically to be able to jump out of a variable initializer :).

**Comment by cybergsus** [comment]
> hmm, are you sure you actually want that to work? as it is now match is a statement with a result. doing the continue will only make sense if you dont use the result, otherwise the continue doesnt really seem well defined. i.e. what exactly do you expect to happen here: `let a = match x { None => continue};` ?

You never end up using that binding, so it's OK to jump out. In Rust `continue` and `break` as well as `return` have an implicit `!` (never) type, which just means that the code that gave control to that block isn't getting the control back (which means that it doesn't matter if the expression is ill-formed, since it won't be observed)

**Comment by cybergsus** [comment]
Codegen needs some book-keeping about what is allowed in the C++ source it's emitting to use a macro that expands to use `continue` and `break` as well as `return` or to use one that just expands `return`.

**Comment by maddanio** [comment]
heads up: my PR around the codegen for match just got merged, so you may want to rebase if you already on it.
