### ISSUE TITLE
parser: Return statements must always have a value

### ISSUE THREAD

**Issue by mattco98** [SerenityOS/jakt#436]
Early returns in functions which do not return a value are current impossible, as the parser will always attempt to parse an expression after a `return` keyword.

**Comment by sagering** [comment]
I think `EOL` (end of line) is supposed to terminate a statement. It would be intersting to discuss wether the void return should be handled as return with an expression of implicit type `void` or as a special case.

As a side note,  this example would also be ambiguous without that rule of `EOL`  termination ( `return (1 + 3 - 1)` or `return 1` ?).

```
function f() -> i32 {
    return 1
    +3 - 1
    let x = 10
}
```

**Comment by dipeshkaphle** [comment]
I just checked, EOL is indeed terminating a statement. I got confused because of the example I gave. It was parsing the following line as an expression for return, which made me believe Eol didn't matter. But seeing the code for parsing expression it makes sense why that happened. Thanks. I'll try to make a pr for this issue

**Comment by 0GreenClover0** [comment]
Seems to be fixed by https://github.com/SerenityOS/jakt/commit/c213b581ce544d2882d7b13a0e48ae40ad00aeb8
