### ISSUE TITLE
C++ compilation error when returning this

### ISSUE THREAD

**Issue by mnlrsn** [SerenityOS/jakt#500]
To reproduce, compile the following snippet:
```
class A {
    function f(this)  {
        return this
    }   
}
```
Error message:
```
error: no viable conversion from returned value of type 'const A *' to function return type 'NonnullRefPtr<A>'
```

**Comment by gysddn** [comment]
Looking into it 👍🏻

**Comment by gysddn** [comment]
The problem is, when returning 'this' the return type of the function is deduced as 'NonnullRefPoint<A>' where as the type of 'this'
is const A* because the function is const qualified. Now the question is that is this pointer going to be a const or not. Should I remove the const qualifier and return a NonnullRefPoint like this:

```
NonnullRefPtr<A> A::f()
{
    {
        return adopt_ref(*this);
    }
}
```

Or a pointer to a const A, like this:
```
NonnullRefPtr<const A> A::f() const
{
    {
        return adopt_ref(*this);
    }
}
```
